; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "FadCrypt"
#define MyAppVersion "v0.3.0"
#define MyAppPublisher "FadSec Lab"
#define MyAppURL "https://faded.dev"
#define MyAppExeName "FadCrypt.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{DAE875C2-596C-4888-87E3-8609F0F72E8E}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run
; on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the
; install be done in "64-bit mode" on x64 or Windows 11 on Arm,
; meaning it should use the native 64-bit Program Files directory and
; the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64compatible
DisableProgramGroupPage=yes
; Uncomment the following line to run in non administrative install mode (install for current user only.)
;PrivilegesRequired=lowest
OutputDir=C:\Users\faded\Desktop\FadCrypt\setup
OutputBaseFilename=FadCryptSetup
SetupIconFile=C:\Users\faded\Documents\repos\FadCrypt\img\1.ico
Compression=lzma
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "C:\Users\faded\Documents\repos\FadCrypt\dist\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

[UninstallRun]
; Run cleanup to restore system settings before uninstalling
Filename: "{app}\{#MyAppExeName}"; Parameters: "--cleanup"; Flags: runhidden waituntilterminated

[Registry]
; Register context menu during installation
Root: HKCU; Subkey: "Software\Classes\*\shell\FadCryptLock"; ValueType: string; ValueName: ""; ValueData: "Lock with FadCrypt"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Classes\*\shell\FadCryptLock"; ValueType: string; ValueName: "Icon"; ValueData: "{app}\{#MyAppExeName},0"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Classes\*\shell\FadCryptLock\command"; ValueType: string; ValueName: ""; ValueData: """{app}\core\windows\FadCryptLock.bat"" ""%1"""; Flags: uninsdeletekey

Root: HKCU; Subkey: "Software\Classes\*\shell\FadCryptUnlock"; ValueType: string; ValueName: ""; ValueData: "Unlock with FadCrypt"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Classes\*\shell\FadCryptUnlock"; ValueType: string; ValueName: "Icon"; ValueData: "{app}\{#MyAppExeName},0"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Classes\*\shell\FadCryptUnlock\command"; ValueType: string; ValueName: ""; ValueData: """{app}\core\windows\FadCryptUnlock.bat"" ""%1"""; Flags: uninsdeletekey

Root: HKCU; Subkey: "Software\Classes\Directory\shell\FadCryptLock"; ValueType: string; ValueName: ""; ValueData: "Lock with FadCrypt"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Classes\Directory\shell\FadCryptLock"; ValueType: string; ValueName: "Icon"; ValueData: "{app}\{#MyAppExeName},0"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Classes\Directory\shell\FadCryptLock\command"; ValueType: string; ValueName: ""; ValueData: """{app}\core\windows\FadCryptLock.bat"" ""%1"""; Flags: uninsdeletekey

Root: HKCU; Subkey: "Software\Classes\Directory\shell\FadCryptUnlock"; ValueType: string; ValueName: ""; ValueData: "Unlock with FadCrypt"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Classes\Directory\shell\FadCryptUnlock"; ValueType: string; ValueName: "Icon"; ValueData: "{app}\{#MyAppExeName},0"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Classes\Directory\shell\FadCryptUnlock\command"; ValueType: string; ValueName: ""; ValueData: """{app}\core\windows\FadCryptUnlock.bat"" ""%1"""; Flags: uninsdeletekey

