; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "FadCrypt"
#define MyAppVersion "v2.0.0"
#define MyAppPublisher "FadSec Lab"
#define MyAppURL "https://faded.dev"
#define MyAppExeName "FadCrypt.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{DAE875C2-596C-4888-87E3-8609F0F72E8E}}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={localappdata}\FadCrypt
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run
; on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the
; install be done in "64-bit mode" on x64 or Windows 11 on Arm,
; meaning it should use the native 64-bit Program Files directory and
; the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64compatible
DisableProgramGroupPage=yes
; Admin privileges required for service installation
PrivilegesRequired=admin
OutputDir=..\dist
OutputBaseFilename=FadCryptSetup
SetupIconFile=..\img\1.ico
Compression=lzma
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
; Desktop icons checkbox - CHECKED by default and NOT optional
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"

[Files]
; Copy GUI build to gui subdirectory with its own _internal
; FadCrypt.exe in gui\ will find _internal\ in the same directory
Source: "..\dist\FadCrypt\FadCrypt.exe"; DestDir: "{app}\gui"; Flags: ignoreversion
Source: "..\dist\FadCrypt\_internal\*"; DestDir: "{app}\gui\_internal"; Flags: recursesubdirs ignoreversion createallsubdirs

; Copy CLI build to cli subdirectory with its own _internal
; fadcrypt.exe in cli\ will find _internal\ in the same directory
Source: "..\dist\FadCryptCLI\fadcrypt.exe"; DestDir: "{app}\cli"; Flags: ignoreversion
Source: "..\dist\FadCryptCLI\_internal\*"; DestDir: "{app}\cli\_internal"; Flags: recursesubdirs ignoreversion createallsubdirs

; Copy image assets for shortcuts
Source: "..\img\1.ico"; DestDir: "{app}\img"; Flags: ignoreversion
Source: "..\img\fadcrypt_cli_ico.ico"; DestDir: "{app}\img"; Flags: ignoreversion
Source: "..\img\fadcrypt_cli.png"; DestDir: "{app}\img"; Flags: ignoreversion

[Icons]
; GUI shortcuts - point to FadCrypt.exe in gui subdirectory
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\gui\{#MyAppExeName}"; Parameters: "--gui"; WorkingDir: "{app}"; IconFilename: "{app}\img\1.ico"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\gui\{#MyAppExeName}"; Parameters: "--gui"; Tasks: desktopicon; WorkingDir: "{app}"; IconFilename: "{app}\img\1.ico"

; CLI shortcuts - point to fadcrypt.exe in cli subdirectory
Name: "{autoprograms}\FadCrypt CLI"; Filename: "{app}\cli\fadcrypt.exe"; Parameters: "--cli"; WorkingDir: "{app}"; IconFilename: "{app}\img\fadcrypt_cli_ico.ico"
Name: "{autodesktop}\FadCrypt CLI"; Filename: "{app}\cli\fadcrypt.exe"; Parameters: "--cli"; Tasks: desktopicon; WorkingDir: "{app}"; IconFilename: "{app}\img\fadcrypt_cli_ico.ico"

[Run]
; Register context menu during install - use --gui to ensure no terminal window
Filename: "{app}\gui\{#MyAppExeName}"; Parameters: "--gui --register-context --internal-auth"; Flags: runhidden skipifsilent waituntilterminated

; Install and start the elevated service for persistent admin rights
Filename: "{app}\gui\{#MyAppExeName}"; Parameters: "--gui --install-service --internal-auth"; Flags: runhidden waituntilterminated

[UninstallRun]
; Stop and uninstall the elevated service
Filename: "{app}\gui\{#MyAppExeName}"; Parameters: "--gui --uninstall-service --internal-auth"; Flags: runhidden waituntilterminated; RunOnceId: "FadCryptServiceUninstall"

; Run cleanup to restore system settings before uninstalling
Filename: "{app}\gui\{#MyAppExeName}"; Parameters: "--gui --cleanup --internal-auth"; Flags: runhidden waituntilterminated; RunOnceId: "FadCryptCleanup"

[Registry]
; Add CLI directory to PATH for command-line access (fadcrypt --cli from anywhere)
Root: HKCU; Subkey: "Environment"; ValueType: expandsz; ValueName: "Path"; ValueData: "{olddata};{app}\cli"; Flags: uninsdeletevalue

