; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "FadCrypt"
#define MyAppVersion "v2.0.0"
#define MyAppPublisher "FadSec Lab"
#define MyAppURL "https://faded.dev"
#define MyAppExeName "FadCrypt.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{DAE875C2-596C-4888-87E3-8609F0F72E8E}}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={localappdata}\FadCrypt
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run
; on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the
; install be done in "64-bit mode" on x64 or Windows 11 on Arm,
; meaning it should use the native 64-bit Program Files directory and
; the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64compatible
DisableProgramGroupPage=yes
; Install for current user only (no admin privileges needed)
PrivilegesRequired=lowest
OutputDir=..\dist
OutputBaseFilename=FadCryptSetup
SetupIconFile=..\img\1.ico
Compression=lzma
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
; Copy entire FadCrypt directory (onedir format) with all subdirectories
Source: "..\dist\FadCrypt\*"; DestDir: "{app}"; Flags: recursesubdirs ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; WorkingDir: "{app}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon; WorkingDir: "{app}"

[Run]
; Register context menu and add CLI PATH entry during install. We call the installed exe with
; --register-context so the app doesn't need to do first-run registry changes.
; This MUST run on every install to ensure context menu is registered.
Filename: "{app}\{#MyAppExeName}"; Parameters: "--register-context"; Flags: runhidden skipifsilent waituntilterminated

[UninstallRun]
; Run cleanup to restore system settings before uninstalling
Filename: "{app}\{#MyAppExeName}"; Parameters: "--cleanup"; Flags: runhidden waituntilterminated; RunOnceId: "FadCryptCleanup"

[Registry]
; Add FadCrypt to PATH for CLI access
Root: HKCU; Subkey: "Environment"; ValueType: expandsz; ValueName: "Path"; ValueData: "{olddata};{app}"; Flags: uninsdeletevalue

; Context menu entries are now handled by the cleanup script, not InnoSetup
; This prevents conflicts during uninstallation

